### ISSUE TITLE
Multiple Files?

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/place-my-order#2]
Should we do everything in one file or multiple files?  Maybe "fewer" files?  Is that possible?

**Comment by justinbmeyer** [comment]
```
    <script src="libs/jquery.js"></script>
    <script src="libs/can.jquery.min.js"></script>
    <script src="libs/can.fixture.js"></script>
    <script src="libs/can.map.define.js"></script>
    <script src="libs/can.stache.js"></script>
    <script src="libs/can.view.href.js"></script>
    <script src="models/city.js"></script>
    <script src="models/fixtures/fixtures.js"></script>
    <script src="models/restaurant.js"></script>
    <script src="models/state.js"></script>
    <script src="models/order.js"></script>
    <script src="order/order.js"></script>
    <script src="order/phone/phone.js"></script>
    <script src="order/history/history.js"></script>
    <script src="order/history/item/item.js"></script>
    <script src="restaurant/details/details.js"></script>
    <script src="restaurant/list/list.js"></script>
    <script src="routes.js"></script>
    <script src="app.js"></script>
```

**Comment by daffl** [comment]
One option (since we don't demonstrate how to use a module loader) would be to create a `models.js` and `components.js` file. Maybe combine `app.js` and `routes.js` into one.

**Comment by chasenlehara** [comment]
I agree with combining `app.js` and `routes.js`. It would be nice to combine the dependencies too.

As for the others, I think that we would be instructing the reader to mostly add each component separately as we covered different topics, so I don’t think it’s as big of a deal to have them all broken up and encourage the separation.

**Comment by justinbmeyer** [comment]
@daffl shouldn't `<script src="libs/can.view.href.js"></script>` be in core?  Can you make that happen?

Maybe we could flatten the filesystem out?  Have everything in a models  or components folder?

```
models/fixtures.js
components/restaurant_list
components/order
```

etc?

**Comment by daffl** [comment]
Oh I din't know that it should become a core plugin. I can change that and update the build.
