### ISSUE TITLE
Custom Styles

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/place-my-order#4]
There's a lot of bootstrappy class names:

``` html
<div class="form-group">
          <label class="control-label">Name:</label>
          <input name="name" type="text" class="form-control" can-keyup="{order.attr 'name' @element.val}">
          <p>Please enter your name.</p>
        </div>
```

I was under the impression that the CanJS guide would not need this sorta thing.

CC @akagomez @tomgreever

**Comment by tomgreever** [comment]
I understood that we wanted to avoid using too many class names, or class names that didn't describe the markup. For example, `text-success align-center pull-left`

In this example, this seems like an appropriate amount / kind. I wasn't trying to avoid using Bootstrap names completely, just avoid an overuse when its not helpful. 

If that's incorrect, we can tweak.

**Comment by akagomez** [comment]
Darn. I must've not hit "send" yesterday. 

Removing classnames from the markup was something I was passionate about. Though I hadn't expected that @tomgreever would be accountable for that during the design phase. If anything it's something I had personally committed myself to doing during development.

**Comment by justinbmeyer** [comment]
```
<div>
          <label>Name:</label>
          <input name="name" type="text" can-keyup="{order.attr 'name' @element.val}">
          <p>Please enter your name.</p>
</div>
```
